### ISSUE TITLE
Support for Rails 4.1, 4.2 etc.

### ISSUE THREAD

**Issue by IevgenRagulin** [zlx/simple_form_bootstrap3#2]
Here is what I see in the gemspec:
  s.add_dependency('activemodel', '>= 4.0.0', '< 4.1')
  s.add_dependency('actionpack', '>= 4.0.0', '< 4.1')

Does this mean that Rails versions 4.1, 4.2 aren't supported? Is there a plan to support them? Is there a fork of this project that has support for the newer Rails versions?

**Comment by zlx** [comment]
Hi, Thank you for so much concern.

The project is not in active maintenance, Just use https://github.com/plataformatec/simple_form since it support for bootstrap 3 & 4 now.

**Comment by IevgenRagulin** [comment]
Thank you for your response. Moving to plataformatec/simple_form worked for me
